project:
  type: website
  resources:
    - "google*.html"  # Keeps your Google Search Console verification file alive

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://njtalingting.r-universe.dev/packages
        text: Software

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    favicon: images/logo.svg
    include-in-header: schema.html
